using System.Diagnostics;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using Microsoft.Extensions.Hosting;
using Npgsql;
using RabbitMQ.Client;
using RabbitMQ.Client.Events;

var builder=Host.CreateApplicationBuilder(args);builder.Services.AddHostedService<Worker>();await builder.Build().RunAsync();

[JsonUnmappedMemberHandling(JsonUnmappedMemberHandling.Disallow)]
public sealed class Envelope {
 [JsonPropertyName("message_id")] public Guid MessageId{get;set;} [JsonPropertyName("event_type")] public string EventType{get;set;}="";
 [JsonPropertyName("event_version")] public int EventVersion{get;set;} [JsonPropertyName("correlation_id")] public Guid CorrelationId{get;set;}
 [JsonPropertyName("causation_id")] public Guid? CausationId{get;set;} [JsonPropertyName("id_orden")] public string IdOrden{get;set;}="";
 [JsonPropertyName("timestamp")] public DateTimeOffset Timestamp{get;set;} [JsonPropertyName("source")] public string Source{get;set;}="";
 [JsonPropertyName("attempt")] public int Attempt{get;set;} [JsonPropertyName("payload")] public JsonObject Payload{get;set;}=new();
}

public sealed class Worker:BackgroundService {
 const string Service="facturacion",Exchange="fisi.ordenes.exchange",Dlx="fisi.ordenes.dlx",Queue="cola_facturacion";
 readonly string db=Environment.GetEnvironmentVariable("DATABASE_URL")??"Host=postgres;Database=db_facturacion;Username=facturacion_user;Password=facturacion_dev";
 readonly int maxRetries=int.Parse(Environment.GetEnvironmentVariable("MAX_RETRIES")??"3"),retryDelay=int.Parse(Environment.GetEnvironmentVariable("RETRY_DELAY_MS")??"5000");
 readonly JsonSerializerOptions json=new(){PropertyNamingPolicy=null,UnmappedMemberHandling=JsonUnmappedMemberHandling.Disallow};
 protected override async Task ExecuteAsync(CancellationToken stop){await Init(stop);var delay=1;while(!stop.IsCancellationRequested){try{await Consume(stop);delay=1;}catch(Exception ex){Console.Error.WriteLine(JsonSerializer.Serialize(new{timestamp=DateTimeOffset.UtcNow,level="ERROR",service=Service,language="csharp",action="reconexion",result=ex.Message}));await Task.Delay(TimeSpan.FromSeconds(delay),stop);delay=Math.Min(delay*2,30);}}}
 async Task Init(CancellationToken ct){for(var i=0;;i++){try{await using var c=new NpgsqlConnection(db);await c.OpenAsync(ct);await using var cmd=new NpgsqlCommand("""CREATE TABLE IF NOT EXISTS facturas(numero_factura TEXT PRIMARY KEY,id_orden TEXT NOT NULL UNIQUE,cliente_id TEXT NOT NULL,nombre_cliente TEXT NOT NULL,ruc_cliente TEXT NOT NULL,subtotal NUMERIC(14,2) NOT NULL,igv NUMERIC(14,2) NOT NULL,total NUMERIC(14,2) NOT NULL,fecha_emision TIMESTAMPTZ DEFAULT NOW());CREATE TABLE IF NOT EXISTS detalle_factura(id BIGSERIAL PRIMARY KEY,numero_factura TEXT NOT NULL REFERENCES facturas(numero_factura),codigo_articulo TEXT NOT NULL,cantidad INT NOT NULL,precio_unitario NUMERIC(14,2) NOT NULL,subtotal NUMERIC(14,2) NOT NULL);CREATE TABLE IF NOT EXISTS mensajes_procesados(message_id UUID PRIMARY KEY,id_orden TEXT NOT NULL,procesado_en TIMESTAMPTZ DEFAULT NOW());""",c);await cmd.ExecuteNonQueryAsync(ct);return;}catch when(i<44){await Task.Delay(2000,ct);}}}
 async Task Consume(CancellationToken stop){var f=new ConnectionFactory{HostName=Environment.GetEnvironmentVariable("RABBITMQ_HOST")??"rabbitmq",UserName=Environment.GetEnvironmentVariable("RABBITMQ_USER")??"fisi",Password=Environment.GetEnvironmentVariable("RABBITMQ_PASSWORD")??"fisi_dev",RequestedHeartbeat=TimeSpan.FromSeconds(30),RequestedConnectionTimeout=TimeSpan.FromSeconds(30),DispatchConsumersAsync=true,AutomaticRecoveryEnabled=true};using var conn=f.CreateConnection();using var ch=conn.CreateModel();ch.BasicQos(0,1,false);ch.ConfirmSelect();var consumer=new AsyncEventingBasicConsumer(ch);consumer.Received+=async(_,ea)=>await Receive(ch,ea,stop);ch.BasicConsume(Queue,false,consumer);Log(null,"consumidor_iniciado","success",0);while(conn.IsOpen&&!stop.IsCancellationRequested)await Task.Delay(1000,stop);}
 async Task Receive(IModel ch,BasicDeliverEventArgs ea,CancellationToken ct){var sw=Stopwatch.StartNew();Envelope? e=null;try{e=JsonSerializer.Deserialize<Envelope>(ea.Body.Span,json)??throw new JsonException("evento nulo");Validate(e,ea.RoutingKey);var result=await Process(ch,e,ct);ch.BasicAck(ea.DeliveryTag,false);Log(e,result=="duplicate"?"mensaje_ignorado_idempotencia":"factura_generada",result,sw.ElapsedMilliseconds);}catch(JsonException ex){ch.BasicNack(ea.DeliveryTag,false,false);Log(e,"mensaje_no_procesable",ex.Message,sw.ElapsedMilliseconds);}catch(Exception ex){if(e is null){ch.BasicNack(ea.DeliveryTag,false,false);return;}await Retry(ch,ea,e,ex.Message,ct);ch.BasicAck(ea.DeliveryTag,false);}}
 static void Validate(Envelope e,string key){if(e.EventType!="factura.generar"||e.EventType!=key||e.EventVersion!=1||e.Attempt<0||!e.Payload.ContainsKey("cliente")||e.Payload["items"] is not JsonArray items||items.Count==0||!e.Payload.ContainsKey("reserva_id")||e.Payload["trace"] is not JsonArray)throw new JsonException("contrato factura.generar invalido");var allowed=new[]{"cliente","items","reserva_id","trace"};if(e.Payload.Any(x=>!allowed.Contains(x.Key)))throw new JsonException("propiedad desconocida en payload");}
 async Task<string> Process(IModel channel,Envelope e,CancellationToken ct){await using var c=new NpgsqlConnection(db);await c.OpenAsync(ct);await using var tx=await c.BeginTransactionAsync(ct);await using(var duplicate=new NpgsqlCommand("SELECT 1 FROM mensajes_procesados WHERE message_id=$1",c,tx)){duplicate.Parameters.AddWithValue(e.MessageId);if(await duplicate.ExecuteScalarAsync(ct)!=null){await tx.RollbackAsync(ct);return"duplicate";}}
   string number;decimal subtotal=0,igv,total;await using(var find=new NpgsqlCommand("SELECT numero_factura,subtotal,igv,total FROM facturas WHERE id_orden=$1",c,tx)){find.Parameters.AddWithValue(e.IdOrden);await using var r=await find.ExecuteReaderAsync(ct);if(await r.ReadAsync(ct)){number=r.GetString(0);subtotal=r.GetDecimal(1);igv=r.GetDecimal(2);total=r.GetDecimal(3);await r.CloseAsync();}else{await r.CloseAsync();foreach(var n in e.Payload["items"]!.AsArray()){var item=n!.AsObject();subtotal+=item["cantidad"]!.GetValue<int>()*item["precio_unitario"]!.GetValue<decimal>();}subtotal=Math.Round(subtotal,2);igv=Math.Round(subtotal*0.18m,2);total=subtotal+igv;number=$"F001-{Guid.NewGuid().ToString("N")[..8].ToUpperInvariant()}";var cli=e.Payload["cliente"]!.AsObject();await using var insert=new NpgsqlCommand("INSERT INTO facturas VALUES($1,$2,$3,$4,$5,$6,$7,$8,NOW())",c,tx);insert.Parameters.AddWithValue(number);insert.Parameters.AddWithValue(e.IdOrden);insert.Parameters.AddWithValue(cli["cliente_id"]!.GetValue<string>());insert.Parameters.AddWithValue(cli["nombre_cliente"]!.GetValue<string>());insert.Parameters.AddWithValue(cli["ruc_cliente"]!.GetValue<string>());insert.Parameters.AddWithValue(subtotal);insert.Parameters.AddWithValue(igv);insert.Parameters.AddWithValue(total);await insert.ExecuteNonQueryAsync(ct);foreach(var n in e.Payload["items"]!.AsArray()){var item=n!.AsObject();await using var d=new NpgsqlCommand("INSERT INTO detalle_factura(numero_factura,codigo_articulo,cantidad,precio_unitario,subtotal) VALUES($1,$2,$3,$4,$5)",c,tx);var qty=item["cantidad"]!.GetValue<int>();var price=item["precio_unitario"]!.GetValue<decimal>();d.Parameters.AddWithValue(number);d.Parameters.AddWithValue(item["codigo_articulo"]!.GetValue<string>());d.Parameters.AddWithValue(qty);d.Parameters.AddWithValue(price);d.Parameters.AddWithValue(qty*price);await d.ExecuteNonQueryAsync(ct);}}}
   var payload=(JsonObject)e.Payload.DeepClone();payload["numero_factura"]=number;payload["subtotal"]=subtotal;payload["igv"]=igv;payload["total"]=total;var trace=payload["trace"]!.AsArray();trace.Add(new JsonObject{{"estado","FACTURADA"},{"evento","factura.generar"},{"message_id",e.MessageId.ToString()},{"causation_id",e.CausationId?.ToString()},{"descripcion",$"Factura creada/reutilizada: {number}."}});var next=Next(e,"cuenta.crear",payload);Publish(channel,"cuenta.crear",next);await using(var done=new NpgsqlCommand("INSERT INTO mensajes_procesados(message_id,id_orden) VALUES($1,$2)",c,tx)){done.Parameters.AddWithValue(e.MessageId);done.Parameters.AddWithValue(e.IdOrden);await done.ExecuteNonQueryAsync(ct);}await tx.CommitAsync(ct);return"cuenta.crear";}
 Envelope Next(Envelope e,string type,JsonObject payload)=>new(){MessageId=Guid.NewGuid(),EventType=type,EventVersion=1,CorrelationId=e.CorrelationId,CausationId=e.MessageId,IdOrden=e.IdOrden,Timestamp=DateTimeOffset.UtcNow,Source=Service,Attempt=0,Payload=payload};
 void Publish(IModel ch,string key,Envelope e,string exchange=Exchange){var body=Encoding.UTF8.GetBytes(JsonSerializer.Serialize(e,json));var p=ch.CreateBasicProperties();p.Persistent=true;p.ContentType="application/json";p.ContentEncoding="utf-8";p.MessageId=e.MessageId.ToString();p.CorrelationId=e.CorrelationId.ToString();ch.BasicPublish(exchange,key,true,p,body);if(!ch.WaitForConfirms(TimeSpan.FromSeconds(10)))throw new Exception("publisher confirm timeout");}
 async Task Retry(IModel ch,BasicDeliverEventArgs ea,Envelope e,string reason,CancellationToken ct){e.Attempt++;e.Timestamp=DateTimeOffset.UtcNow;e.Source=Service;if(e.Attempt>maxRetries){var compensation=Next(e,"reserva.liberar",(JsonObject)e.Payload.DeepClone());e.EventType="error.tecnico";Publish(ch,"error.tecnico",e,Dlx);Publish(ch,"reserva.liberar",compensation);}else{await Task.Delay(retryDelay,ct);Publish(ch,ea.RoutingKey,e);}Log(e,"fallo_tecnico",e.Attempt>maxRetries?"dlq_y_compensacion":$"retry:{reason}",0);}
 static void Log(Envelope? e,string action,string result,long ms)=>Console.WriteLine(JsonSerializer.Serialize(new{timestamp=DateTimeOffset.UtcNow,level="INFO",service=Service,language="csharp",event_type=e?.EventType,message_id=e?.MessageId,correlation_id=e?.CorrelationId,causation_id=e?.CausationId,id_orden=e?.IdOrden,attempt=e?.Attempt??0,action,result,duration_ms=ms}));
}
