import amqp, {ConfirmChannel, ConsumeMessage} from "amqplib";
import {createServer} from "node:http";
import {randomUUID} from "node:crypto";
import {Pool, PoolClient} from "pg";

const SERVICE="reserva", EXCHANGE="fisi.ordenes.exchange", DLX="fisi.ordenes.dlx", QUEUE="cola_reserva";
const pool=new Pool({connectionString:process.env.DATABASE_URL??"postgresql://reserva_user:reserva_dev@postgres:5432/db_reserva",connectionTimeoutMillis:30000});
const maxRetries=Number(process.env.MAX_RETRIES??3), retryDelay=Number(process.env.RETRY_DELAY_MS??5000);

export interface Envelope {message_id:string;event_type:string;event_version:1;correlation_id:string;causation_id:string|null;id_orden:string;timestamp:string;source:string;attempt:number;payload:Record<string,unknown>}
type Item={codigo_articulo:string;nombre_articulo:string;cantidad:number;precio_unitario:number};
const now=()=>new Date().toISOString();
function validate(v:unknown,key:string):asserts v is Envelope {
  if(!v||typeof v!=="object"||Array.isArray(v))throw new Error("envelope no es objeto");
  const e=v as Record<string,unknown>, allowed=["message_id","event_type","event_version","correlation_id","causation_id","id_orden","timestamp","source","attempt","payload"];
  if(Object.keys(e).some(k=>!allowed.includes(k))||e.event_type!=="reserva.crear"||e.event_type!==key||e.event_version!==1||!Number.isInteger(e.attempt)||Number(e.attempt)<0)throw new Error("envelope invalido");
  const p=e.payload as Record<string,unknown>; if(!p||!Array.isArray(p.items)||p.items.length===0||!p.cliente||!Array.isArray(p.trace))throw new Error("payload invalido");
}
function log(e:Partial<Envelope>,action:string,result:string,ms=0){console.log(JSON.stringify({timestamp:now(),level:"INFO",service:SERVICE,language:"typescript",event_type:e.event_type,message_id:e.message_id,correlation_id:e.correlation_id,causation_id:e.causation_id,id_orden:e.id_orden,attempt:e.attempt??0,action,result,duration_ms:ms}));}
async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS reservas(id_reserva TEXT PRIMARY KEY,id_orden TEXT NOT NULL UNIQUE,estado TEXT NOT NULL,fecha_reserva TIMESTAMPTZ DEFAULT NOW());CREATE TABLE IF NOT EXISTS detalle_reserva(id BIGSERIAL PRIMARY KEY,id_reserva TEXT NOT NULL REFERENCES reservas(id_reserva),codigo_articulo TEXT NOT NULL,cantidad INT NOT NULL,UNIQUE(id_reserva,codigo_articulo));CREATE TABLE IF NOT EXISTS mensajes_procesados(message_id UUID PRIMARY KEY,id_orden TEXT NOT NULL,procesado_en TIMESTAMPTZ DEFAULT NOW())`);}
async function publish(ch:ConfirmChannel,key:string,e:Envelope,exchange=EXCHANGE){ch.publish(exchange,key,Buffer.from(JSON.stringify(e),"utf8"),{persistent:true,contentType:"application/json",contentEncoding:"utf-8",messageId:e.message_id,correlationId:e.correlation_id});await ch.waitForConfirms();}
function next(e:Envelope,type:string,payload:Record<string,unknown>):Envelope{return{message_id:randomUUID(),event_type:type,event_version:1,correlation_id:e.correlation_id,causation_id:e.message_id,id_orden:e.id_orden,timestamp:now(),source:SERVICE,attempt:0,payload};}
async function processEvent(ch:ConfirmChannel,e:Envelope):Promise<string>{
  const client=await pool.connect();try{await client.query("BEGIN");const duplicate=await client.query("SELECT 1 FROM mensajes_procesados WHERE message_id=$1",[e.message_id]);if(duplicate.rowCount){await client.query("ROLLBACK");return"duplicate";}
    let found=await client.query("SELECT id_reserva FROM reservas WHERE id_orden=$1",[e.id_orden]);let id:string;
    if(found.rowCount){id=found.rows[0].id_reserva;}else{id=`RES-${randomUUID().slice(0,8).toUpperCase()}`;await client.query("INSERT INTO reservas(id_reserva,id_orden,estado) VALUES($1,$2,'ACTIVA')",[id,e.id_orden]);for(const item of e.payload.items as Item[]){if(!item.codigo_articulo||!Number.isInteger(item.cantidad)||item.cantidad<1||typeof item.precio_unitario!=="number")throw new Error("item invalido");await client.query("INSERT INTO detalle_reserva(id_reserva,codigo_articulo,cantidad) VALUES($1,$2,$3) ON CONFLICT DO NOTHING",[id,item.codigo_articulo,item.cantidad]);}}
    const trace=[...(e.payload.trace as object[]),{estado:"RESERVADA",evento:"reserva.crear",message_id:e.message_id,causation_id:e.causation_id,descripcion:`Reserva creada/reutilizada: ${id}.`}];const out=next(e,"factura.generar",{...e.payload,reserva_id:id,trace});await publish(ch,out.event_type,out);await client.query("INSERT INTO mensajes_procesados(message_id,id_orden) VALUES($1,$2)",[e.message_id,e.id_orden]);await client.query("COMMIT");return"factura.generar";
  }catch(err){await client.query("ROLLBACK");throw err;}finally{client.release();}}
async function retry(ch:ConfirmChannel,msg:ConsumeMessage,raw:Envelope,reason:string){raw.attempt=(raw.attempt??0)+1;raw.timestamp=now();raw.source=SERVICE;if(raw.attempt>maxRetries){raw.event_type="error.tecnico";await publish(ch,"error.tecnico",raw,DLX);}else{await new Promise(r=>setTimeout(r,retryDelay));await publish(ch,msg.fields.routingKey,raw);}ch.ack(msg);log(raw,"fallo_tecnico",raw.attempt>maxRetries?"dlq":`retry:${reason}`);}
async function connectForever(){let delay=1000;for(;;){try{const connection=await amqp.connect({hostname:process.env.RABBITMQ_HOST??"rabbitmq",username:process.env.RABBITMQ_USER??"fisi",password:process.env.RABBITMQ_PASSWORD??"fisi_dev",heartbeat:30});const ch=await connection.createConfirmChannel();await ch.prefetch(1);await ch.consume(QUEUE,async msg=>{if(!msg)return;const started=Date.now();let raw:unknown;try{raw=JSON.parse(msg.content.toString("utf8"));validate(raw,msg.fields.routingKey);const result=await processEvent(ch,raw);ch.ack(msg);log(raw,result==="duplicate"?"mensaje_ignorado_idempotencia":"reserva_creada",result,Date.now()-started);}catch(err){if(raw&&typeof raw==="object")await retry(ch,msg,raw as Envelope,String(err));else ch.nack(msg,false,false);}},{noAck:false});log({},"consumidor_iniciado","success");await new Promise<void>(resolve=>connection.on("close",resolve));delay=1000;}catch(err){console.error(JSON.stringify({timestamp:now(),level:"ERROR",service:SERVICE,language:"typescript",action:"reconexion",result:String(err)}));await new Promise(r=>setTimeout(r,delay));delay=Math.min(delay*2,30000);}}}
async function main(){await init();createServer(async(_,res)=>{try{await pool.query("SELECT 1");res.writeHead(200,{"content-type":"application/json"});res.end('{"status":"ok","service":"reserva","language":"typescript"}');}catch{res.writeHead(503);res.end();}}).listen(8082);await connectForever();}
if(require.main===module)main().catch(err=>{console.error(err);process.exit(1);});
