services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: fisi-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - fisi_backend

volumes:
  rabbitmq_data:

networks:
  fisi_backend:
    driver: bridge
